### ISSUE TITLE
Missing recent quotes

### ISSUE THREAD

**Issue by bbatsov** [LubomirGeorgiev/bnb-currency-exchange-rates#3]
I've noticed that most exchange rates haven't been updated in the past six months (e.g. https://raw.githubusercontent.com/LubomirGeorgiev/bnb-currency-exchange-rates/main/data/GBP.csv) Perhaps the update cron job is broken?

One more thing - what does "missing" mean exactly in the data sets? I've noticed the column, but I'm not sure what is it supposed to signify.

**Comment by LubomirGeorgiev** [comment]
Sorry for the late response.

I completely rewrote the whole script and now the data is being stored in an SQLite database, because there were some data consistency issues with the CSV implementation. You can have a look at the `main` branch.

The Bulgarian National Bank doesn't publish exchange rates during weekends and national holidays, so the term `missing` in this context signifies whether or not the data point was backfilled with the previous one that was available. For example since exchange rates are not available on Saturday they will be backfilled with the rate from Friday.

**Comment by LubomirGeorgiev** [comment]
I will close this one for now since it was opened while the CSV implementation was still available but now it's all rewritten.

Please have a look at the new SQLite implementation and open a new issue (it will be even better if you fix it and open a pull request :D) if you see any inconsistencies.
